### PR TITLE
Prepare the release 3.6

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
Increase the level of the code from 3.5 to 3.6.

I'm missing some things here?

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
@IzzySoft This PR has the point to make a new apk signed, any comment on it before we merge it? :)

**Comment by IzzySoft** [comment]
LGTM: `versionCode` is increased and `versionName` adjusted. So it will show up as version 3.6 and should be offered for update :smiley:

**Review by lvaccaro — APPROVED** [review]
ack 4d6e2cfa2d9c3f57e11445fab58593f513dee39b

nit: suggest to change commit message

**Comment by vincenzopalazzo** [comment]
> nit: suggest to change commit message

Commit message changed @lvaccaro :)

>LGTM: versionCode is increased and versionName adjusted. So it will show up as version 3.6 and should be offered for update smiley

Cool, we will work to have an official release for this night :)

**Comment by IzzySoft** [comment]
> Cool, we will work to have an official release for this night :)

Should it arrive before 7pm UTC, it will even be part of today's sync to my repo :smiley:

**Comment by vincenzopalazzo** [comment]
>Should it arrive before 5pm UTC, it will even be part of today's sync to my repo smiley

Sorry for the early arrival :) https://github.com/clightning4j/lamp/releases/tag/release_3.6

**Comment by IzzySoft** [comment]
Yes, just had my surprise with the bot announcing it. Glad you made it, thanks! It's live now :smiley: So all worked out fine as the update was pulled automatically :+1:

**Pull request merged**
